export const menuLst = [
  // {
  //   id: "1",
  //   type: 1,
  //   name: "故障预案",
  //   icon: "cpu",
  //   hidden: false,
  //   children: [
  //     {
  //       id: "1-1",
  //       type: 2,
  //       name: "容器扩缩容",
  //       icon: "",
  //       url: "/main/kube/deployment",
  //     },
  //     {
  //       id: "1-2",
  //       type: 2,
  //       name: "容器应急保障",
  //       icon: "",
  //       url: "/main/kube/pod",
  //     },
  //     {
  //       id: "1-3",
  //       type: 2,
  //       name: "Event事件查询",
  //       icon: "search",
  //       url: "/main/kube/event",
  //     },
  //   ],
  // },
  {
    id: "2",
    type: 1,
    name: "故障管理",
    icon: "monitor",
    hidden: false,
    children: [
      {
        id: "2-1",
        type: 2,
        name: "故障运营",
        icon: "",
        url: "/main/fault/list",
      },
      {
        id: "2-2",
        type: 2,
        name: "故障改进",
        icon: "",
        url: "/main/fault/improve",
      },
      // {
      //   id: "2-3",
      //   type: 2,
      //   name: "故障预算",
      //   icon: "",
      //   url: "/main/fault/budget",
      // },
    ],
  },
  {
    id: "3",
    type: 1,
    name: "事件管理",
    icon: "",
    children: [
      {
        id: "3-1",
        type: 2,
        name: "事件中心",
        icon: "",
        url: "/main/event/display",
      },
    ],
  },
  {
    id: "4",
    type: 1,
    name: "数据管理",
    icon: "",
    children: [
      {
        id: "4-1",
        type: 2,
        name: "数据看板",
        icon: "",
        url: "/monitor/kanban",
      },
      {
        id: "4-2",
        type: 2,
        name: "应用看板",
        icon: "",
        url: "/monitor/scope",
      },
      // {
      //   id: "4-2",
      //   type: 2,
      //   name: "拨测系统",
      //   icon: "",
      //   url: "/monitor/dialing",
      // },
      // {
      //   id: "4-3",
      //   type: 2,
      //   name: "告警事件",
      //   icon: "",
      //   url: "/monitor/alarm",
      // },
    ],
  },
  {
    id: "5",
    type: 1,
    name: "故障工具",
    icon: "",
    children: [
      {
        id: "5-1",
        type: 2,
        name: "拨测系统",
        icon: "",
        url: "/monitor/dialing",
      },
      // {
      //   id: "4-3",
      //   type: 2,
      //   name: "告警事件",
      //   icon: "",
      //   url: "/monitor/alarm",
      // },
    ],
  },
];
